### ISSUE TITLE
SQL Error on v2.0 RC1 Upgrade

### ISSUE THREAD

**Issue by Jaben** [YAFNET/YAFNET#26]
System.Exception: FILE:
mssql/constraints.sql

ERROR:
The ALTER TABLE statement conflicted with the FOREIGN KEY constraint "FK_yaf_GroupMedal_yaf_Group". The conflict occurred in database "YAF", table "dbo.yaf_Group", column 'GroupID'.

STATEMENT:
if not exists (select top 1 1 from  sys.objects where name='FK_yaf_GroupMedal_yaf_Group' and parent_object_id=object_id('[dbo].[yaf_GroupMedal]') and type in (N'F'))
    alter table [dbo].[yaf_GroupMedal] add constraint [FK_yaf_GroupMedal_yaf_Group] foreign key(GroupID) references [dbo].[yaf_Group](GroupID)
   at YAF.Classes.Data.LegacyDb.system_initialize_executescripts(String script, String scriptFile, Boolean useTransactions) in c:\TeamCity\buildAgent\work\486389e89d993eec\yafsrc\YAF.Classes\YAF.Classes.Data\mssql\LegacyDb.cs:line 6127
   at YAF.Core.Services.InstallUpgradeService.ExecuteScript(String scriptFile, Boolean useTransactions) in c:\TeamCity\buildAgent\work\486389e89d993eec\yafsrc\YAF.Core\Services\InstallUpgradeService.cs:line 353
   at YAF.Core.Services.InstallUpgradeService.UpgradeDatabase(Boolean fullText, Boolean upgradeExtensions) in c:\TeamCity\buildAgent\work\486389e89d993eec\yafsrc\YAF.Core\Services\InstallUpgradeService.cs:line 262
   at YAF.Install._default.Wizard_NextButtonClick(Object sender, WizardNavigationEventArgs e)
   at System.Web.UI.WebControls.Wizard.OnBubbleEvent(Object source, EventArgs e)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by Pistle** [comment]
Inspect Server Settings
Open your SQL Server Configuration Manager. 
Expand SQL Server Network Configuration and select Protocols for SQLEXPRESS. 
Take a look at TCP/IP, which requires to be Enabled. 
Also, you may take a look at the Port setting of your server. 
Click the IP Address tab in the TCP/IP Properties dialog box.
