### ISSUE TITLE
SqlException when updating stats on certain cases

### ISSUE THREAD

**Issue by tbolon** [YAFNET/YAFNET#344]
Since last week-end, we had a problem with the default forum page, where users were receiving an error.

The error log was displaying the following message:

```
Exception System.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_yaf_TopicReadTracking_yaf_Topic". The conflict occurred in database "xxx", table "dbo.yaf_TopicReadTracking", column 'TopicID'.
  at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
  at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
  at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
  at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
  at System.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
  at System.Data.SqlClient.SqlDataReader.NextResult()
  at System.Data.Common.DataAdapter.FillNextResult(DataReaderContainer dataReader)
  at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
  at System.Data.Common.DataAdapter.Fill(DataSet dataSet, String srcTable, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
  at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
  at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
  at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
  at YAF.Types.Interfaces.Data.IDbAccessExtensions.<>c__DisplayClass7.<GetDataset>b__6(IDbCommand c)
  at YAF.Core.Data.DbAccessBase.Execute[T](Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction)
  at YAF.Types.Interfaces.Data.IDbAccessExtensions.GetData(IDbAccess dbAccess, IDbCommand cmd, IDbTransaction dbTransaction)
  at YAF.Core.Data.DynamicDbFunction.<InvokeGetData>b__5(IDbCommand cmd)
  at YAF.Core.Data.DynamicDbFunction.DbFunctionExecute(DbFunctionType functionType, InvokeMemberBinder binder, IList`1 parameters, Func`2 executeDb, Object& result)
  at YAF.Core.Data.DynamicDbFunction.InvokeGetData(InvokeMemberBinder binder, Object[] args, Object& result)
  at CallSite.Target(Closure , CallSite , Object , Int32 , Boolean , Boolean , Int32 )
  at YAF.Core.Model.BoardRepositoryExtensions.Poststats(IRepository`1 repository, Int32 boardID, Boolean styledNicks, Boolean showNoCountPosts)
  at YAF.Controls.ForumStatistics.<ForumStatistics_Load>b__28_2()
  at YAF.Core.Services.Cache.HttpRuntimeCache.GetOrSetInternal[T](String key, Func`1 getValue, Action`1 addToCacheFunction)
  at YAF.Core.Services.Cache.HttpRuntimeCache.GetOrSet[T](String key, Func`1 getValue, TimeSpan timeout)
  at YAF.Controls.ForumStatistics.ForumStatistics_Load(Object sender, EventArgs e)
  at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive()
  at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive()
  at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive()
  at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

The fix was to update the board_poststats SP to delete yaf_TopicReadTracking before deleting from yaf_Topic.

I will submit a PR.

**Comment by tbolon** [comment]
See my PR for a fix.
