### ISSUE TITLE
Error in DNN Yaf 2.23.5743

### ISSUE THREAD

**Issue by marietteknap** [YAFNET/YAFNET#355]
Sometimes I get this:

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:dbe93785-1222-4114-9055-2ce866790784
AssemblyVersion:8.0.4
PortalId:0
UserId:28771
TabId:154
RawUrl:/forum/g/postmessage/t/181/f/1/windows-server-essentials
Referrer:https://www.server...m/forum/g/postmessage/t/181/f/1/windows-server-essentials
UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
ExceptionHash:zwvl+0Q3pnOTNZCR251png==
Message:Value cannot be null. Parameter name: source
StackTrace:

InnerMessage:Value cannot be null. Parameter name: source
InnerStackTrace:
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at YAF.Modules.PageTitleForumModule.GeneratePageTitle()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

What can I do to prevent this from happening?

**Comment by w8tcha** [comment]
This is an known issue. I already fixed this with cb5abb3bfa6b2e13aabeee56e5c24e1ce16cf708 this will fixed with the next version
