### ISSUE TITLE
The invoked member is not supported in a dynamic assembly in janus.Windows.TimeLine

### ISSUE THREAD

**Issue by srmathivanan** [YAFNET/YAFNET#399]
when assign New Janus.Windows.TimeLine.TimeLine  throws error

 System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   at System.Reflection.Assembly.get_EscapedCodeBase()
   at Janus.Windows.TimeLine.JNSAN.a(Type , Assembly )
   at Janus.Windows.TimeLine.JNSAN.GetSavedLicenseKey(Type type, Assembly resourceAssembly)
   at Janus.Windows.TimeLine.TimeLineLicenseProvider.GetLicense(LicenseContext context, Type type, Object instance, Boolean allowExceptions)
   at System.ComponentModel.LicenseManager.ValidateInternalRecursive(LicenseContext context, Type type, Object instance, Boolean allowExceptions, License& license, String& licenseKey)
   at System.ComponentModel.LicenseManager.Validate(Type type, Object instance)

please help......

**Comment by w8tcha** [comment]
Wrong project
