### ISSUE TITLE
Delete a Post Fails in DNN

### ISSUE THREAD

**Issue by tonyatl2** [YAFNET/YAFNET#602]
**Describe the bug**
When attempting to delete a post, yaf fails with critical error message - and says to see admin logs

**To Reproduce**

1. install the latest dnn yaf.net module available on 1/26/2021
2. go to the test topic in the test forum (i renamed the category) logged in as host
3. post a comment with an attachment
4. go away for a few hours
5. log in as host to dnn
6. navigate to the post posted above
7. click the post menu on the right of the screen
8. click the Delete Post item
9. yaf.net crashes with message to see admin logs

**Expected behavior**
I expected yaf.net to delete the post, including the image

**Screenshots**

**System (please complete the following information):**
 - YAF Version: 2.3.1.12
 - .NET Version [e.g. 4.xxx] I am running Windows Server 2019 with latest updates
 - SQL Server [e.g. SQL Server 2017]
 - DNN 9.8.1
 
**Affected browser**

* [X ] Chrome 87.0.4280.141 (Official Build) (64-bit)
* [ ] Firefox
* [ ] Safari
* [ ] Edge

**Additional context**
from the dnn admin log:

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:34c6053b-f791-46f3-8570-07c61efdfc9b

AssemblyVersion:9.8.1

PortalId:0

UserId:1

TabId:69

RawUrl:/forums2/g/DeleteMessage/m/1/action/delete

Referrer:https://www.etiquemarket.com/forums2/g/Posts/t/1/test

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

ExceptionHash:S6+ugjs/wxJ/USp3tRHvVHXyEVw=

Message:Nullable object must have a value.

StackTrace:

InnerMessage:Nullable object must have a value.

InnerStackTrace:

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at YAF.Web.BBCodes.Attach.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at YAF.Utils.Helpers.ControlHelper.RenderToString(Control control)
   at YAF.Web.Controls.MessageBase.<>c__DisplayClass3_0.<RenderModulesInBBCode>b__0(KeyValuePair`2 keyPair)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at YAF.Web.Controls.MessageBase.RenderModulesInBBCode(HtmlTextWriter writer, String message, MessageFlags theseFlags, Nullable`1 displayUserId, Nullable`1 messageId)
   at YAF.Web.Controls.MessagePost.RenderMessage(HtmlTextWriter writer)
   at YAF.Web.Controls.MessagePost.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at YAF.Core.ForumPage.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at YAF.Web.Controls.Forum.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.WebControls.WebControl.RenderContents(HtmlTextWriter writer)
   at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at DotNetNuke.UI.Modules.ModuleHost.RenderContents(HtmlTextWriter writer)
   at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at ASP.portals__default_skins_minis_page_69_forums2_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer)
   at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer)
   at System.Web.UI.Adapters.ControlAdapter.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

**Comment by w8tcha** [comment]
Issue is fixed in 2.31.13
