### ISSUE TITLE
When I click on the "TEAM" link on the main menu, I get the following ERROR

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#672]
When I click on the "TEAM" link on the main menu, I get the following ERROR:

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Web.HttpException (0x80004005): DataBinding: 'YAF.Types.Models.User' does not contain a property with the name 'ModeratorID'.
at System.Web.UI.DataBinder.GetPropertyValue(Object container, String propName)
at System.Web.UI.DataBinder.Eval(Object container, String[] expressionParts)
at ASP.pages_team_ascx.__DataBinding__control25(Object sender, EventArgs e) in c:\inetpub\wwwroot\aspx-daprose-yaf\Pages\Team.ascx:line 66
at System.Web.UI.Control.OnDataBinding(EventArgs e)
at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
at System.Web.UI.Control.DataBindChildren()
at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
at System.Web.UI.WebControls.Repeater.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem)
at System.Web.UI.WebControls.Repeater.AddDataItemsIntoItemsArray(IEnumerable dataSource, Boolean useDataSource)
at System.Web.UI.WebControls.Repeater.PostGetDataAction(IEnumerable dataSource)
at System.Web.UI.WebControls.Repeater.OnDataBinding(EventArgs e)
at System.Web.UI.Control.DataBindChildren()
at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at System.Web.UI.Control.OnLoad(EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
at System.Web.UI.Page.d__523.MoveNext()
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
at System.Web.UI.Page.d__515.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.UI.Page.d__554.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
at ASP.default_aspx.EndProcessRequest(IAsyncResult ar) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\forums\276e2450\e630afe\App_Web_vd31j4hl.2.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)**Describe the bug**

**To Reproduce**
1. Login as the Administrator. It doesn't show the TEAM ling if a regular user'
2. Click on 'TEAM'
3. See the error page immediately:

**Expected behavior**

**Screenshots**

![Yanet-Error](https://user-images.githubusercontent.com/95335292/157833392-b4568e88-5300-4a1e-a9af-1c16535abf75.png)

**System (please complete the following information):**
 - YAF Version: 3.1.2
 - .NET Version 4.8
 - SQL Server SQL Server 2019
 
**Affected browser**

* [ ] Chrome
* [ x ] Firefox
* [ ] Safari
* [ ] Edge

**Comment by daprose-dotcom** [comment]
<h2> <i>DataBinding: 'YAF.Types.Models.User' does not contain a property with the name 'ModeratorID'.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during 
the execution of the current web request. Please review the stack trace 
for more information about the error and where it originated in the 
code.

            <br><br>

            <b> Exception Details: </b>System.Web.HttpException: DataBinding: 'YAF.Types.Models.User' does not contain a property with the name 'ModeratorID'.<br><br>

            <b>Source Error:</b> <br><br>

            

Line 64:                                                      TitleLocalizedPage="POSTS" TitleLocalizedTag="EMAIL_TITLE" Line 65:                                                      Icon="at" Type="Secondary" /> Line 66:                                     <YAF:ThemeButton ID="AdminUserButton" runat="server" Line 67:                                                      TitleLocalizedPage="PROFILE" TitleLocalizedTag="ADMIN_USER" Line 68:                                                      TextLocalizedTag="ADMIN_USER" TextLocalizedPage="PROFILE"
--

**Comment by w8tcha** [comment]
Issue fixed with Commit 1e4fc27dcba3c4c94c6c4e17f281a8e753f21141
