### ISSUE TITLE
Unable to cast object of type 'YAF.Configuration.BoardSettings' to type 'YAF.Core.BoardSettings.LoadBoardSettings'.

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#719]
From the latest source and in a new installation when you try to save settings in Host Settings > Features > Display Settings ,The following exception is thrown:

Exception Details: System.InvalidCastException: Unable to cast object of type 'YAF.Configuration.BoardSettings' to type 'YAF.Core.BoardSettings.LoadBoardSettings'.

Line 319:
Line 320:        // save the settings to the database
Line 321:        ((LoadBoardSettings)this.PageBoardContext.BoardSettings).SaveRegistry();
Line 322:
Line 323:        this.Get<LinkBuilder>().Redirect(ForumPages.Admin_Admin);

Source File: C:\Users\User\Desktop\yafsrc\YetAnotherForum.NET\Pages\Admin\HostSettings.ascx.cs    Line: 321

**Comment by SinaBina** [comment]
And also the following error is logged in the event log of forum probably related to the same error in Registry:

```
Error In UpdateSearchIndexTask Task
System.InvalidCastException: Unable to cast object of type 'YAF.Configuration.BoardSettings' to type 'YAF.Core.BoardSettings.LoadBoardSettings'.
   at YAF.Core.Tasks.UpdateSearchIndexTask.IsTimeToUpdateSearchIndex() in C:'Users'User'Desktop'yafsrc'YAF.Core'Tasks'UpdateSearchIndexTask.cs:line 123
   at YAF.Core.Tasks.UpdateSearchIndexTask.RunOnce() in C:'Users'User'Desktop'yafsrc'YAF.Core'Tasks'UpdateSearchIndexTask.cs:line 85
```
