### ISSUE TITLE
Exception when deleting all private messages

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#766]
In the latest source under: User Menu > My Inbox > Sent Items > Delete All throws the following exception:

`Exception of type 'System.Web.HttpUnhandledException' was thrown. (User-IP: 127.0.0.1 | URL:'http://localhost:50165/Default.aspx?g=MyMessages')
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Data.SqlClient.SqlException (0x80131904): An expression of non-boolean type specified in a context where a condition is expected, near ')'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at ServiceStack.OrmLite.OrmLiteCommand.ExecuteReader() in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'OrmLiteCommand.cs:line 108
   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.ExecReader(IDbCommand dbCmd, String sql) in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'OrmLiteReadCommandExtensions.cs:line 59
   at ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ExprConvertToList[T](IDbCommand dbCmd, String sql, IEnumerable`1 sqlParams, HashSet`1 onlyFields) in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'OrmLiteResultsFilterExtensions.cs:line 209
   at ServiceStack.OrmLite.ReadExpressionCommandExtensions.Select[T](IDbCommand dbCmd, Expression`1 predicate) in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'Expressions'ReadExpressionCommandExtensions.cs:line 47
   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.<>c__DisplayClass30_0`1.<Select>b__0(IDbCommand dbCmd) in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'OrmLiteReadExpressionsApi.cs:line 418
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter) in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'OrmLiteExecFilter.cs:line 177
   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Exec[T](IDbConnection dbConn, Func`2 filter) in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'OrmLiteReadExpressionsApi.cs:line 33
   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Select[T](IDbConnection dbConn, Expression`1 predicate) in C:'Users'User'Desktop'yafsrc'ServiceStack'ServiceStack.OrmLite'OrmLiteReadExpressionsApi.cs:line 418
   at YAF.Core.Extensions.IRepositoryExtensions.<>c__DisplayClass16_0`1.<Get>b__0(IDbCommand db) in C:'Users'User'Desktop'yafsrc'YAF.Core'Extensions'IRepositoryExtensions.cs:line 495
   at YAF.Core.Data.DbAccessBase.Execute[T](Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction) in C:'Users'User'Desktop'yafsrc'YAF.Core'Data'DbAccessBase.cs:line 99
   at YAF.Core.Extensions.IRepositoryExtensions.Get[T](IRepository`1 repository, Expression`1 criteria) in C:'Users'User'Desktop'yafsrc'YAF.Core'Extensions'IRepositoryExtensions.cs:line 495
   at YAF.Controls.PMList.DeleteAll_Click(Object source, EventArgs e) in C:'Users'User'Desktop'yafsrc'YetAnotherForum.NET'Controls'PMList.ascx.cs:line 173
   at YAF.Web.Controls.ThemeButton.OnClick(EventArgs e) in C:'Users'User'Desktop'yafsrc'YAF.Web'Controls'ThemeButton.cs:line 703
   at YAF.Web.Controls.ThemeButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) in C:'Users'User'Desktop'yafsrc'YAF.Web'Controls'ThemeButton.cs:line 429
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
ClientConnectionId:d4ebab83-603b-4ec8-8122-62fcf6b4cf17
Error Number:4145,State:1,Class:15
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.default_aspx.EndProcessRequest(IAsyncResult ar) in c:'Users'User'AppData'Local'Temp'Temporary ASP.NET Files'vs'90b5084c'e86377db'App_Web_psddbh2t.2.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

**Comment by SinaBina** [comment]
The error is no longer present but "Delete All" button does not delete any messages now.It is in an upgraded database from 1.9.6

**Comment by w8tcha** [comment]
Are the messages still show up under User Menu > My Inbox > Sent Items?

**Comment by SinaBina** [comment]
Yes and pop up box says 0 message deleted!

**Comment by w8tcha** [comment]
it should be fixed now

**Comment by SinaBina** [comment]
> it should be fixed now

It is fixed but it counts deleted message wrongly.For example I deleted 7 messages (Sent Folder) and it said "2 messages were removed"

**Comment by w8tcha** [comment]
I removed the not working counter

**Comment by SinaBina** [comment]
> I removed the not working counter
It was helpful knowing how many messages you have deleted/archived!

**Comment by w8tcha** [comment]
i re-added the count, can you verify if it works?

**Comment by SinaBina** [comment]
The archive section is gone and is not shown any more.
The counter still shows wrong information.
To test I send message to all users the go to "sent" section and hit "delete all" although messages are removed but the counter is wrong.

**Comment by w8tcha** [comment]
Can you please describe the steps to reproduce the issue? Also how to verify that the counter is wrong?

**Comment by SinaBina** [comment]
> Can you please describe the steps to reproduce the issue? Also how to verify that the counter is wrong?

Sure, 
[PM.zip](https://github.com/YAFNET/YAFNET/files/9542490/PM.zip)

**Comment by SinaBina** [comment]
Find out something interesting, If you hit the "Delete All" button of Inbox folder, it deletes all messages whether in inbox or Sent and it counts "**Correctly**" but if you hit the "Delete All" button of Sent folder, it counts 0

**Comment by w8tcha** [comment]
Okay found the problem. Issue(s) should be fixed now

**Comment by SinaBina** [comment]
> Find out something interesting, If you hit the "Delete All" button of Inbox folder, it deletes all messages whether in inbox or Sent and it counts "**Correctly**" but if you hit the "Delete All" button of Sent folder, it counts 0

Now it is Vice-versa, "Delete All" button of **Inbox** does not delete any messages and "Delete All" button of **Sent** works and counts fine 😄

**Comment by w8tcha** [comment]
Okay another fix attempt

**Comment by SinaBina** [comment]
There are still couple of issues. Please take a look at video. Thanks.

[PM Issues.zip](https://github.com/YAFNET/YAFNET/files/9545730/PM.Issues.zip)

**Comment by w8tcha** [comment]
The video is very confusing. I dont understand the problem. Can you describe the problem? and the steps to reproduce it? 

Is the counter still wrong or not?

**Comment by SinaBina** [comment]
The main problem related to this ticket is that the counter of "**Sent**" folder when hitting "**Delete All**" button is wrong and everything else (including deleting all messages in inbox folder and counter) works fine.

But there is another issue with data view. As you have noticed in **User > My Settings > Edit Settings > Standard Page Size** is set to show 5 entries. In the first page of my inbox, it shows 10 entries in the second page shows 5 and in the third page shows 2.I think there is something wrong with binding/caching.

**Comment by w8tcha** [comment]
> The main problem related to this ticket is that the counter of "**Sent**" folder when hitting "**Delete All**" button is wrong and everything else (including deleting all messages in inbox folder and counter) works fine.

  
So just to be clear before you wrote 

> Now it is Vice-versa, "Delete All" button of **Inbox** does not delete any messages and "Delete All" button of **Sent** works and counts fine :smile:

So now youre saying the opposite. At this point i think its better to remove the counter.

**Comment by SinaBina** [comment]
First of all thing **THANKYOU** for your wonderful dedication.It is really appreciable.
I just test and try to be as helpful as possible. So please excuse me if I can't be.

At this stage as everything is working fine and there is only 1 small issue, I suggest to not to remove it, so that we have more time to fix it in the future.

**Comment by w8tcha** [comment]
The count for both inbox and outbox should be correct now
