### ISSUE TITLE
Opening private messages throws exception

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#769]
In the latest source and in an upgrade scenario from 1.9.6 opening **some** private messages throw exception.For example opening the _http://localhost:50165/PrivateMessage?pm=7780&v=out_ is OK but _http://localhost:50165/PrivateMessage?pm=7777&v=out_ cause exception and the following error is logged:

`Exception of type 'System.Web.HttpUnhandledException' was thrown. (User-IP: 127.0.0.1 | URL:'http://localhost:50165/Default.aspx?g=PrivateMessage&pm=7777&v=out')
System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at YAF.Core.Model.PMessageRepositoryExtensions.<>c.<GetReplies>b__6_0(PagedPm m) in C:'Users'User'Desktop'yafsrc'YAF.Core'Model'PMessageRepositoryExtensions.cs:line 494
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at YAF.Core.Model.PMessageRepositoryExtensions.GetReplies(IRepository`1 repository, List`1 messages) in C:'Users'User'Desktop'yafsrc'YAF.Core'Model'PMessageRepositoryExtensions.cs:line 494
   at YAF.Core.Model.PMessageRepositoryExtensions.List(IRepository`1 repository, Int32 userPMessageID, Boolean includeReplies) in C:'Users'User'Desktop'yafsrc'YAF.Core'Model'PMessageRepositoryExtensions.cs:line 444
   at YAF.Pages.PrivateMessage.BindData() in C:'Users'User'Desktop'yafsrc'YetAnotherForum.NET'Pages'PrivateMessage.ascx.cs:line 128
   at YAF.Pages.PrivateMessage.Page_Load(Object sender, EventArgs e) in C:'Users'User'Desktop'yafsrc'YetAnotherForum.NET'Pages'PrivateMessage.ascx.cs:line 108
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestAsync>d__515.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.UI.Page.<ProcessRequestAsync>d__554.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at ASP.default_aspx.EndProcessRequest(IAsyncResult ar) in c:'Users'User'AppData'Local'Temp'Temporary ASP.NET Files'vs'90b5084c'e86377db'App_Web_trt25frv.2.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

[Object reference not set to an instance of an object.zip](https://github.com/YAFNET/YAFNET/files/9539745/Object.reference.not.set.to.an.instance.of.an.object.zip)

**Comment by w8tcha** [comment]
I added a error handle, at the moment i can not reproduce the issue

**Comment by SinaBina** [comment]
> I added a error handle, at the moment i can not reproduce the issue
It now goes to line 455 of "C:\Users\User\Desktop\yafsrc\YAF.Core\Model\PMessageRepositoryExtensions.cs" and gives:
`m is null` exception:

![Untitled](https://user-images.githubusercontent.com/5496007/189516477-d111c728-a71b-46b7-a0a3-af3e300a1214.png)

**Comment by w8tcha** [comment]
When you hover over messages is it also null?

**Comment by SinaBina** [comment]
> When you hover over messages is it also null?
Hovering over messages shows nothing (no popup) while hovering over their usernames show popup.

**Comment by w8tcha** [comment]
no i mean inside vs when the exeption occurs like seen in the screenshot

**Comment by SinaBina** [comment]
Sorry w8tcha, I don't get what you say,You mean hovering the mouse over the variable "messages" ?
![Untitled2](https://user-images.githubusercontent.com/5496007/189518896-c97f4a8b-49bd-4ea2-bd7e-09f64dd80618.png)
![Uploading Untitled1.png…]()

**Comment by w8tcha** [comment]
> Sorry w8tcha, I don't get what you say,You mean hovering the mouse over the variable "messages" ?

Correct, i need to know if it is null or not

**Comment by SinaBina** [comment]
> > Sorry w8tcha, I don't get what you say,You mean hovering the mouse over the variable "messages" ?
> 
> Correct, i need to know if it is null or not

You mean this:
![Untitled](https://user-images.githubusercontent.com/5496007/189525141-a5122f88-45b0-4265-bee0-8218bd69a56a.png)

**Comment by w8tcha** [comment]
Sorrry i forgot you need to set a break point first on that line, then it should look like that when hover over the message when you run the debugger

![](https://user-images.githubusercontent.com/722575/189527602-a68cc2c7-b0b1-4f05-b1b3-b227c7e8ecc5.png)

**Comment by SinaBina** [comment]
I can not reproduce the issue in latest commit as the problematic PMs where in "Archive" folder. The rest are OK now.

**Comment by w8tcha** [comment]
But your initial report was about the oubox (Send items) not the archive. So this can be closed since there is no more useless archive

**Comment by SinaBina** [comment]
Yes true. There was 2 in inbox and 1 in archive but looks like the null handler did the job.
I agree with you on the uselessness of archive but the question is what happens to the messages in archive folder of old users? Are they moved to inbox? 
Probably there has been a reason behind archiving PM maybe for later reference or else.

**Comment by w8tcha** [comment]
Correct the messages are not deleted. Archiving doesnt work since messages are displayed now similar as topics where all replies are shown.
