### ISSUE TITLE
Active Users not functioning as expected

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#816]
It appears that the Active Users only shows the members active if you're Administrator. Otherwise, you see this below.
![image](https://user-images.githubusercontent.com/5612416/201717583-ec7a1dd1-6135-47e0-96ee-458d056a9823.png)

Under my admin account, this is shown.
![image](https://user-images.githubusercontent.com/5612416/201717655-eec3976a-be40-42dd-ba52-28c6816a1d2c.png)

Regardless of admin or regular account, if you click "# guests" link, no guests are displayed. If you click "# active users", you then see the guests listed.
![image](https://user-images.githubusercontent.com/5612416/201717969-96cc97d0-d811-452c-a18b-7b396d486ee4.png)

No errors or anything to mention.

**Comment by KevinDuganJr** [comment]
This has not been fixed. 

![image](https://user-images.githubusercontent.com/5612416/202194284-748df772-e32b-4432-9689-7a57692ce616.png)

**Comment by w8tcha** [comment]
I cannot reproduce this. Are you running on the latest commit?

**Comment by w8tcha** [comment]
Okay, i was able to reproduce it. and also to fix it

**Comment by KevinDuganJr** [comment]
I'm not sure it is fixed. When I run the latest commit and click on active users, or members or guests, I get this.


`````System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=PageSize must be a number greater than 0.
Parameter name: pageSize
  Source=YAF.Core
  StackTrace:
   at YAF.Core.Extensions.SqlExpressionExtensions.Page[T](SqlExpression`1 expression, Nullable`1 page, Nullable`1 pageSize) in C:\Users\kduganjr\source\repos\KevinDuganJr\YAFNET\yafsrc\YAF.Core\Extensions\SqlExpressionExtensions.cs:line 61
   at YAF.Core.Model.ActiveRepositoryExtensions.<>c__DisplayClass3_0.<ListUsersPaged>b__0(IDbCommand db) in C:\Users\kduganjr\source\repos\KevinDuganJr\YAFNET\yafsrc\YAF.Core\Model\ActiveRepositoryExtensions.cs:line 321
   at YAF.Core.Data.DbAccessBase.Execute[T](Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction) in C:\Users\kduganjr\source\repos\KevinDuganJr\YAFNET\yafsrc\YAF.Core\Data\DbAccessBase.cs:line 99
   at YAF.Core.Model.ActiveRepositoryExtensions.ListUsersPaged(IRepository`1 repository, Int32 userId, Boolean showGuests, Boolean showCrawlers, Int32 pageIndex, Int32 pageSize, Nullable`1 boardId) in C:\Users\kduganjr\source\repos\KevinDuganJr\YAFNET\yafsrc\YAF.Core\Model\ActiveRepositoryExtensions.cs:line 289
   at YAF.Pages.ActiveUsers.GetActiveUsersData(Boolean showGuests, Boolean showCrawlers) in C:\Users\kduganjr\source\repos\KevinDuganJr\YAFNET\yafsrc\YetAnotherForum.NET\Pages\ActiveUsers.ascx.cs:line 229
   at YAF.Pages.ActiveUsers.BindData() in C:\Users\kduganjr\source\repos\KevinDuganJr\YAFNET\yafsrc\YetAnotherForum.NET\Pages\ActiveUsers.ascx.cs:line 171
   at YAF.Pages.ActiveUsers.Page_Load(Object sender, EventArgs e) in C:\Users\kduganjr\source\repos\KevinDuganJr\YAFNET\yafsrc\YetAnotherForum.NET\Pages\ActiveUsers.ascx.cs:line 71
   at System.EventHandler.Invoke(Object sender, EventArgs e)

![image](https://user-images.githubusercontent.com/5612416/202473545-41d8176c-eed6-4aa9-b2e8-e3d70a34dc84.png)

**Comment by w8tcha** [comment]
sorry forgot to update the pages. fixed now
