### ISSUE TITLE
Edit Message intermittently throws error

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#820]
I haven't encountered this with my admin account, but did with my regular account. However, it only happened once and I haven't been able to reproduce it. 

That being said, a different member is having the issue every time he tries to edit a message.  

There's a context menu here in the log so little hard to copy/paste, but here's an image.
![image](https://user-images.githubusercontent.com/5612416/202007850-8bace8c8-ccb5-4254-a789-b354363bea3e.png)

User reported this as the error message.
Server Error in '/' Application.

Nullable object must have a value.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: Nullable object must have a value.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[InvalidOperationException: Nullable object must have a value.] System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) +56 YAF.Pages.EditMessage.CanEditPostCheck(Message message, Topic topicInfo) +137 YAF.Pages.EditMessage.Page_Load(Object sender, EventArgs e) +230 System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +52 System.EventHandler.Invoke(Object sender, EventArgs e) +0 System.Web.UI.Control.OnLoad(EventArgs e) +97 System.Web.UI.Control.LoadRecursive() +61 System.Web.UI.Control.LoadRecursive() +134 System.Web.UI.Control.LoadRecursive() +134 System.Web.UI.Control.LoadRecursive() +134 System.Web.UI.Control.LoadRecursive() +134 System.Web.UI.Control.LoadRecursive() +134 System.Web.UI.Control.LoadRecursive() +134 System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +693

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4494.0

Actually, looking at the Event Log's, I am seeing several users having the same error when attempting to edit a post, and sometimes when posting a message. I'll have to dig into this more so I can provide better details for you to reproduce.

**Comment by w8tcha** [comment]
The issue with editing a message as normal user is fixed. Can you post the error log from posting a message. this should be a different stacktrace

**Comment by KevinDuganJr** [comment]
Delete
[ Clean Up](javascript:__doPostBack('ctl00$MainContent$forum$ctl02$List$ctl01$ctl05',''))
Exception of type 'System.Web.HttpUnhandledException' was thrown.
 
 http://www.packershome.com:80/forum/forum.aspx?g=PostMessage&t=32480&f=4 System.Web
Exception of type 'System.Web.HttpUnhandledException' was thrown.

at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.forum_forum_aspx.ProcessRequest(HttpContext context) in c:'Windows'Microsoft.NET'Framework'v4.0.30319'Temporary ASP.NET Files'root'ffc632ac'f4684724'App_Web_as1ngtmx.0.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by KevinDuganJr** [comment]
It looks like we're getting errors on deleting a message too.

`````Exception of type 'System.Web.HttpUnhandledException' was thrown.

 http://www.packershome.com:80/forum/forum.aspx?g=DeleteMessage&m=454723&action=delete System.Web
Exception of type 'System.Web.HttpUnhandledException' was thrown.

at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context)
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.forum_forum_aspx.ProcessRequest(HttpContext context) in c:'Windows'Microsoft.NET'Framework'v4.0.30319'Temporary ASP.NET Files'root'ffc632ac'f4684724'App_Web_as1ngtmx.0.cs:line 0
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by KevinDuganJr** [comment]
This popped up when I used Quick Reply. Still using the same build as where the other errors are. I haven't implemented the fix for Edit message.

`````Exception at URL: http://packershome.com/forum/forum.aspx?g=posts&m=454740&

 http://packershome.com:80/forum/forum.aspx?g=posts&m=454740& System.Core
One or more errors occurred.

at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
at System.Linq.Parallel.MergeExecutor`1.Execute()
at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
at YAF.Core.Services.SendNotification.ToWatchingUsers(Message message, Boolean newTopic)
at YAF.Dialogs.QuickReply.QuickReplyClick(Object sender, EventArgs e)

**Comment by w8tcha** [comment]
Please do not post different errors in one issue report. It's impossible to follow there are 3 different issues here. Please open a new one for each.
