### ISSUE TITLE
The invoked member is not supported in a dynamic assembly

### ISSUE THREAD

**Issue by jsassner** [YAFNET/YAFNET#97]
I've integrated Yaf as a control in a page with loads of other controls, and it works great. I just updated to 2.1.0 and it works just fine in my dev environment (IIS Express). But when i went live i ran into an issue (IIS 8). I get:

```
The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.GetExportedTypes()
   at YAF.Core.AssemblyExtensions.<>c__DisplayClass2`1.<FindClassesWithAttribute>b__0(Assembly a) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Extensions\AssemblyExtensions.cs:line 55
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at YAF.Core.AssemblyExtensions.FindClassesWithAttribute[T](IEnumerable`1 assemblies) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Extensions\AssemblyExtensions.cs:line 52
   at YAF.Core.Modules.DynamicServicesModule.RegisterDynamicServices(Assembly[] assemblies) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Modules\DynamicServicesModule.cs:line 65
   at YAF.Core.Modules.DynamicServicesModule.Load(ContainerBuilder containerBuilder) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Modules\DynamicServicesModule.cs:line 56
   at YAF.Core.BaseModule.Configure(IComponentRegistry componentRegistry) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Modules\BaseModule.cs:line 105
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at YAF.Core.BaseModule.RegisterBaseModules[TModule](Assembly[] assemblies, IEnumerable`1 exclude) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Modules\BaseModule.cs:line 139
   at YAF.Core.Modules.BootstrapModule.Load(ContainerBuilder builder) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Modules\BootstrapModule.cs:line 48
   at YAF.Core.BaseModule.Configure(IComponentRegistry componentRegistry) in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\Modules\BaseModule.cs:line 105
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at YAF.Core.GlobalContainer..cctor() in e:\tmp\YetAnotherForum.Net.20140112-0d9d7894cc\yafsrc\YAF.Core\GlobalContainer.cs:line 51´
```

So some dynamical generated assembly is loaded, and the code in the exception breaks. I fixed it by adding a filter to YAF.Core.AssemblyExtensions.

```
foreach (
                var types in
                    assemblies.Select(
                        a =>
                        a.GetExportedTypes().Where(t => !t.IsAbstract && t.GetCustomAttributes(attributeType, true).Any()).ToList()))
            {
                moduleClassTypes.AddRange(types);
            }
```

```
foreach (
                var types in
                    assemblies.Where(x => !x.IsDynamic).Select(
                        a =>
                        a.GetExportedTypes().Where(t => !t.IsAbstract && t.GetCustomAttributes(attributeType, true).Any()).ToList()))
            {
                moduleClassTypes.AddRange(types);
            }
```

It works now, but did i fix it correctly?

**Comment by srmathivanan** [comment]
When assign new New Janus.Windows.TimeLine.TimeLine, its throws following error
   at System.Reflection.Emit.InternalAssemblyBuilder.get_CodeBase()
   at System.Reflection.Assembly.get_EscapedCodeBase()
   at Janus.Windows.TimeLine.JNSAN.a(Type , Assembly )
   at Janus.Windows.TimeLine.JNSAN.GetSavedLicenseKey(Type type, Assembly resourceAssembly)
   at Janus.Windows.TimeLine.TimeLineLicenseProvider.GetLicense(LicenseContext context, Type type, Object instance, Boolean allowExceptions)
   at System.ComponentModel.LicenseManager.ValidateInternalRecursive(LicenseContext context, Type type, Object instance, Boolean allowExceptions, License& license, String& licenseKey)
   at System.ComponentModel.LicenseManager.Validate(Type type, Object instance)
   at Janus.Windows.TimeLine.TimeLine.b()
   at Janus.Windows.TimeLine.TimeLine..ctor()
   at AHN.Clarus.Client.Master.RIS.frmQCChart.InitializeComponent() in D:\Mathivanan\Working Area\Source Code\Trunk\Radiology\FE\CommonClient\frmQCChart.vb:line 79
   at AHN.Clarus.Client.Master.RIS.frmQCChart..ctor() in D:\Mathivanan\Working Area\Source Code\Trunk\Radiology\FE\CommonClient\frmQCChart.vb:line 31
   at AHN.Clarus.Client.Master.RIS.frmQC.callViewChart() in D:\Mathivanan\Working Area\Source Code\Trunk\Radiology\FE\CommonClient\frmQC.vb:line 981

Any please hel p me.....
